name: farmora
description: A new Flutter project for Farmora e-commerce app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  firebase_auth: ^4.1.0
  firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
  fonts:
    - family: Abnes
      fonts:
        - asset: assets/fonts/Abnes-Regular.ttf
