name: farmora
description: Flutter Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  connectivity_plus: ^4.0.2
  battery_plus: ^4.0.2
  flutter_blue_plus: ^1.14.1
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
