name: farmora
description: A new Flutter project for Farmora e-commerce app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  cloud_firestore: ^4.17.5
  # System monitoring packages (updated)
  connectivity_plus: ^5.0.1
  battery_plus: ^4.0.2
  flutter_blue_plus: ^1.31.16  # Modern Bluetooth package replacing flutter_bluetooth_serial
  # Added for CRUD operations
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  intl: ^0.18.1  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/profile_photo.png
    - assets/google_logo.png
  fonts:
    - family: Abnes
      fonts:
        - asset: assets/fonts/Abnes-Regular.ttf
